-- ============================================================================
-- ReqPub - seed the "Fathering Excellence Profile" worked-example PRD (standalone; touches nothing else)
-- ============================================================================
-- Run ONCE in the Supabase SQL editor, AFTER schema.sql. Re-runnable (idempotent).
-- It targets the org named exactly 'Collection Ventures'. If your workspace is
-- named differently, change the name on the first line of the DO block.
-- Generated from tools/prd-seed-data.mjs; do not hand-edit.
-- ============================================================================

begin;

do $$
declare v_org uuid;
begin
  select id into v_org from orgs where name = 'Collection Ventures' order by created_at limit 1;
  if v_org is null then
    raise exception 'No workspace named "Collection Ventures" was found. Edit the name in this file and re-run.';
  end if;

  delete from projects where org_id = v_org and id = 'prd-fathering-excellence';

  -- Insert the project shells (owned by the workspace; filled drafts, no version).
  insert into projects (id, org_id, name, disc_export) values
    ('prd-fathering-excellence', v_org, 'Fathering Excellence Profile', false);
end $$;

-- Scalar answers
insert into project_fields (project_id, field_id, value, rev, updated_by_name, updated_at) values
  ('prd-fathering-excellence', 'ctrl_product', '"Fathering Excellence Profile"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_org', '"Collection Ventures"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_owner', '"Micah Canfield"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_status', '"In Review"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_purpose', '"This document is the authoritative requirements record for the Fathers.com continuing-education and community platform. It is written for the build team (PM, CTO, SWE leads) and the build agent, and it defines the vision, roles, experiences, architecture, data model, engagement mechanics, institutional deployment modes, and the phased build plan. Where this record is silent, the build escalates to the owner rather than inventing scope."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_vision', '"Make Fathers.com the number-one global platform where fathers assess where they stand, grow with proven material, lock arms with other men, and prove their progress in ways courts, employers, and their own families can trust. The founding belief, unchanged since 1990: when fathers grow, children flourish. North Star: Weekly Active Fathering Actions (WAFA), the count of fathers who log at least one intentional real-world fathering action in a given week. Business North Star: Verified Completions, the unit institutions pay for."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_problem', '"Fathers lack a trusted way to know where they stand and prove progress. Roughly one in four US children live without a father in the home. Generic parenting apps measure screen time, not fathering, and produce nothing a court, employer, or parole board will accept. The opportunity is a validated instrument plus a proof rail plus real-world brotherhood, three things AI cannot commoditize and men will actually pay for."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_market', '"About 34.3 million US men have a biological child under 18, within roughly 71 million North American fathers. The client segmentation places about 56 percent of fathers as growth-oriented and 44 percent as at-risk across five segments. Institutional buyers already fund fatherhood programming: corrections, courts, employers, and military and VA channels. The first deployment is free for a 100,000-subscriber onboarding wave, with monetization following immediately."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'context', '"Mobile-first installable PWA at 390-point width, one primary action per screen. Corrections mode must run fully offline for a class session and sync when connectivity returns. Institutional modes (employer, court, corrections, military) are configuration bundles over one platform, not separate apps. Assessment must never block on the network; the member is the only thing it waits on."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_solution', '"One platform with a single spine: a validated onboarding assessment (the Keystone Father Profile) that tells every man the truth, a deterministic plan engine that maps his lowest factors to exact modules, region-and-stage-matched Crews of 5 to 8 men with an accountability Anchor, cohort Expeditions that end in a verified completion, a weekly Rhythm of logged real-world actions, a verified-behavior rank ladder (Waypoints), and a signing-and-verification layer (ProofRail) whose records verify independently even if Fathers.com is offline."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'staged', '"Yes"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'has_ai', '"Yes"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'golden', '"Voice mode is evaluated against a human-labeled set of colloquial answers mapped to the 1-to-5 scale, built during the pilot and stratified by dialect cohort. The knowledge agent is evaluated against a probe set of in-corpus and out-of-corpus questions; every generated response must cite a source module, and out-of-corpus probes must trigger honest deferral plus a content-gap ticket, never an improvised answer."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'vulnerable', '"Yes"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'safeguard', '"A disclosure of self-harm, harm to others, or domestic violence routes to a trained human within one hour, pauses all gamification and nudges for that member, and surfaces professional resources in-product. The protocol is never punitive and never automated therapy (runbook RB-04, interaction IX-09). Minors are excluded from the platform in every role; child records are life-stage and birth-year band only."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'consent', '"Research, comparison (self vs observer), and marketing consents are separate records, plain-language, opt-in, and revocable at any time. Research consent is separate from terms acceptance. The self-versus-observer comparison overlay renders only after both the father and the secondary participant accept an identical consent sheet; either revocation removes it immediately."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'retention', '"Responses and scores are retained while the account lives. Self-serve export (JSON plus PDFs) and account deletion carry a 14-day cooldown; deletion cascades per the retention matrix, with certificates preserved as anonymized verification stubs so previously issued proofs still verify. Corrections records follow the facility agreement and applicable records law. The audit log is retained seven years."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'residency', '"Primary data is stored and processed in the platform region on the managed Postgres backend. Cross-border processing for institutional channels is contracted per agreement. Voice audio is processed for transcription and discarded by default; transcripts store with the response record."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'access', '"Row-level security defaults to deny. Members read their own rows; Crew and group visibility flow through membership joins. Assessment scores carry the strictest policy: readable by the member, the scoring service, and consented case access only, and are never visible to employers, courts, corrections officials, or military admins. Institutional roles read only aggregate views with a minimum cohort size of ten. Staff access is scoped by case and logged; production access is break-glass and reviewed monthly."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'verify_note', '"A release is accepted when every Must requirement for the phase passes its fit criterion in production, the RLS default-deny suite passes, and the phase exit criteria in the build plan hold. ProofRail records must verify independently of Fathers.com systems (the Mars rule) with zero false-valids."'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'link_repo', '"to confirm"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'link_board', '"to confirm"'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'link_design', '"to confirm"'::jsonb, 1, 'Seed', now())
on conflict (project_id, field_id) do update set value = excluded.value, rev = 1;

-- Repeating rows (lists and tables). k is the permanent per-field id used for FR-/NFR-style numbering.
insert into field_rows (project_id, field_id, k, data, pos, updated_by_name, updated_at) values
  ('prd-fathering-excellence', 'ov_goals', 1, '{"text":"Grow Weekly Active Fathering Actions (WAFA) week over week as the primary mission metric."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_goals', 2, '{"text":"Produce Verified Completions (assessments, Expeditions, courses) as the fundable business unit, reported weekly by channel."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_goals', 3, '{"text":"Onboard the 100,000-subscriber wave with assessment completion at or above 75 percent of starters."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_goals', 4, '{"text":"Reach Crew join at or above 40 percent of new completers and week-4 Rhythm at or above 45 percent."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'ov_goals', 5, '{"text":"Sign at least one institutional channel (employer, court, corrections, or military) with real revenue."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 1, '{"text":"Instrument-agnostic assessment engine that loads the Keystone Father Profile as configuration and runs multi-session, resumable, autosaving intake."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 2, '{"text":"Deterministic personalization engine mapping factor bands and child life-stage to an ordered plan of three active items."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 3, '{"text":"Crews, Anchors, and leader-run groups with Crew-scoped and Anchor-scoped messaging only."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 4, '{"text":"Weekly Rhythm logging, cohort Expeditions, and a verified-behavior Waypoints rank ladder."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 5, '{"text":"ProofRail signing, timestamping, transparency log, and public certificate verification."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 6, '{"text":"Four institutional deployment modes: employer, court, corrections (offline-capable), and military."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_in', 7, '{"text":"Eyes-free voice assessment (later phase) and a grounded knowledge agent behind the plan (later phase)."}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 1, '{"text":"No infinite-scroll feed; the home screen is a mission board."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 2, '{"text":"No minor accounts and no collection of children’s names, ever."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 3, '{"text":"No open direct messages between strangers; messaging is Crew and Anchor scoped."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 4, '{"text":"No daily platform-wide streak; the Rhythm is weekly, daily cadence only inside Expeditions."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 5, '{"text":"No therapy-speak, clinical claims, or diagnosis; the platform educates and connects, it does not treat."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 6, '{"text":"No dark patterns, no ads, no selling member data, no crypto or tokens."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'sol_out', 7, '{"text":"No chatbot as the front door and no native livestream infrastructure before leader demand proves it."}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'assume', 1, '{"text":"The Keystone Father Profile is psychometrically validated and licensed for digital deployment with existing norms and rubrics (owner-confirmed; item count and observer-form rights confirmed at Phase 0 exit)."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'assume', 2, '{"text":"The 100,000-subscriber onboarding wave exists and converts a meaningful fraction to accounts across the launch arc."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'assume', 3, '{"text":"Institutional buyers pay for verified completion and aggregate reporting, not for assessment scores."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'depend', 1, '{"text":"Managed Postgres backend (Supabase-class) with row-level security, realtime, storage, and edge functions."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'depend', 2, '{"text":"Managed video platform for on-demand modules and embedded third-party livestreams at launch."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'depend', 3, '{"text":"Payment processor with subscription billing, checkout, marketplace payouts, and tax."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'depend', 4, '{"text":"ProofRail verification service shared with the studio’s existing verification work."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'depend', 5, '{"text":"Instrument owner sign-off for any change to scoring, norms, or item structure."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'constrain', 1, '{"text":"One deployment, domain-modular; no microservices at this audience scale."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'constrain', 2, '{"text":"The instrument is configuration; zero instrument logic in code."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'constrain', 3, '{"text":"All working names ship behind config flags for owner rename without code change."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'constrain', 4, '{"text":"WCAG 2.1 AA and Section 508 globally, because federal channels require it."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'constrain', 5, '{"text":"Answer-save p95 under 300 ms; the UI never blocks on the network."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_approvers', 1, '{"role":"Owner","name":"Micah Canfield"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_approvers', 2, '{"role":"Product","name":"Tim Harris"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_approvers', 3, '{"role":"CTO / Architecture","name":"Alon Arad"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'ctrl_approvers', 4, '{"role":"Engineering lead","name":"Erik Companhone"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'seg', 1, '{"segment":"Growth-oriented fathers","share":"56%","desc":"Want a precise next step after the Profile, not a content dump."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'seg', 2, '{"segment":"At-risk fathers","share":"44%","desc":"Span crisis-window, corrections, and reentry situations."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'seg', 3, '{"segment":"Crisis-window fathers","share":"High value","desc":"Separation or custody proceedings; need a court-accepted course with proof, fast."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'seg', 4, '{"segment":"Institutional cohorts","share":"Funded","desc":"Employer, court, corrections, and military buyers who pay for verified completion."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 1, '{"persona":"The Busy Professional","needs":"Multi-session, one-handed mobile, resumable; weekly not daily cadence."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 2, '{"persona":"The Auditory Learner","needs":"Voice assessment and audio-first modules for the commute."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 3, '{"persona":"The Crisis-Window Father","needs":"A court-recognized course with seat-time tracking and public certificate verification."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 4, '{"persona":"The Incarcerated or Reentry Father","needs":"Offline facility delivery, proof usable with parole and child support, and account continuity on release."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 5, '{"persona":"The Veteran Father","needs":"Peer credibility, trauma-informed pacing, no clinical framing, no autoplay of intense material."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'persona', 6, '{"persona":"The Faith-Driven Group Leader","needs":"Curriculum sequencing, attendance, and group progress without seeing member scores."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 1, '{"rel":"Phase 0 Foundation","obj":"Repo, environments, schema and RLS, auth, event pipeline, design system, instrument loader, ProofRail skeleton.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 2, '{"rel":"Phase Spine","obj":"Assess, results, plan, membership; onboard the 100K wave; WAFA dashboard live.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 3, '{"rel":"Phase Brotherhood","obj":"Crews, Anchors, Rhythm, Expeditions, Waypoints, Campfire, crisis protocol, ProofRail issuance.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 4, '{"rel":"Phase Leaders & Commerce","obj":"Leader consoles, store and events, court-track course and public verification.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 5, '{"rel":"Phase Institutions A","obj":"Employer SSO/SCIM and aggregate dashboard; court coordinator portal; SOC 2 evidence begins.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 6, '{"rel":"Phase Institutions B","obj":"Corrections offline mode and Reentry Bridge; military mode; outcome instrumentation for evaluation.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 7, '{"rel":"Phase Voice","obj":"Eyes-free voice assessment with grounded clarification and a dialect evaluation harness.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'release', 8, '{"rel":"Phase Guide","obj":"Grounded knowledge agent behind the plan with mandatory citations and gap tickets.","mvp":"to confirm","ship":"to confirm"}'::jsonb, 8, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 1, '{"name":"Assessment Engine","owner":"Erik Companhone","status":"Planned","desc":"Instrument-agnostic, multi-session, resumable, idempotent write path."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 2, '{"name":"Plan Engine","owner":"Erik Companhone","status":"Planned","desc":"Deterministic factor-to-module mapping; three active items maximum."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 3, '{"name":"Community","owner":"Huy Tran","status":"Planned","desc":"Crews, Anchors, groups, threads, moderation, safeguarding."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 4, '{"name":"Engagement","owner":"Huy Tran","status":"Planned","desc":"Rhythm, Expeditions, Waypoints, notification discipline."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 5, '{"name":"ProofRail","owner":"Alon Arad","status":"Planned","desc":"Signing, RFC 3161 timestamps, transparency log, revocation, public verify."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 6, '{"name":"Institutional Modes","owner":"Andy Lan","status":"Planned","desc":"Employer, court, corrections (offline), military configuration bundles."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 7, '{"name":"Voice Mode","owner":"Erik Companhone","status":"Planned","desc":"Streaming STT, grounded intent, streaming TTS; tap parity always."}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'components', 8, '{"name":"Knowledge Agent","owner":"Erik Companhone","status":"Planned","desc":"Retrieval over the vetted corpus; cited generation; no unvetted claims."}'::jsonb, 8, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 1, '{"metric":"Answer-save latency","target":"p95 under 300 ms","method":"Server-acknowledged timing on the responses write path."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 2, '{"metric":"Assessment completion (starters)","target":"at or above 75%","method":"Completions divided by starts, per launch cohort."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 3, '{"metric":"Crew join rate (new completers)","target":"at or above 40%","method":"Crew joins within 7 days of results."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 4, '{"metric":"Week-4 Rhythm rate","target":"at or above 45%","method":"Members logging in week 4 of membership."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 5, '{"metric":"Expedition cohort completion","target":"at or above 55%","method":"Completions per enrolled cohort."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 6, '{"metric":"Voice semantic mapping accuracy","target":"at or above 95%","method":"Against a human-labeled set; below 92% blocks a dialect cohort."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 7, '{"metric":"WAFA (North Star)","target":"up and to the right, weekly","method":"Distinct fathers logging one intentional action per week."}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'metrics', 8, '{"metric":"Verified Completions (Business North Star)","target":"weekly by channel","method":"ProofRail-signed records issued."}'::jsonb, 8, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 1, '{"stmt":"The platform delivers the Keystone Father Profile as one item per screen on a uniform 1-to-5 scale, autosaving every answer and resuming on any device.","fit":"A member completes the instrument across multiple sessions and devices with no lost answers; save p95 under 300 ms. Test and Demonstration.","pri":"Must","comp":"Assessment Engine"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 2, '{"stmt":"The engine loads an instrument as data (items, sections, dimensions, factors, scale anchors, scoring weights, norm tables, clarifications, observer variant) with no code change per instrument.","fit":"A 100-item and a 138-item instrument both run from configuration. Inspection and Test.","pri":"Must","comp":"Assessment Engine"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 3, '{"stmt":"On completion the platform scores against the licensed rubric and renders results strengths-first, growth-areas-second, norm-referenced in plain words, never a grade, always ending in the member’s first three actions.","fit":"Results match the licensed scoring exactly and always present a trail. Inspection and Test.","pri":"Must","comp":"Plan Engine"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 4, '{"stmt":"The plan engine maps the member’s lowest factors and children’s life-stages to an ordered plan of at most three active items (one module, one field action, one Crew or Expedition step).","fit":"Every member sees exactly three active items derived from mapping tables; recommendation tap-through is measured. Test.","pri":"Must","comp":"Plan Engine"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 5, '{"stmt":"The platform forms Crews of 5 to 8 men matched on child life-stage, region, and situation tags, with an Anchor pairing and a merge offer when a Crew falls below four active men after six weeks.","fit":"New completers are offered a matched Crew; small Crews trigger a merge. Test and Demonstration.","pri":"Must","comp":"Community"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 6, '{"stmt":"Messaging is Crew-scoped and Anchor-scoped only; leaders broadcast and hold public sessions but cannot direct-message members.","fit":"No path exists for a leader-to-member DM or a stranger DM. Inspection and Test.","pri":"Must","comp":"Community"}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 7, '{"stmt":"The Rhythm records one intentional fathering action per week with optional note, with milestone celebrations at 4, 12, 26, and 52 weeks and a protection pass earned per completed Expedition.","fit":"One log per week counts; no daily platform streak exists; milestones fire only at the four marks. Test.","pri":"Must","comp":"Engagement"}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 8, '{"stmt":"Expeditions run fixed-length cohorts with daily check-ins and Crew visibility, and issue a ProofRail-signed completion record on finish.","fit":"A completed Expedition produces a verifiable record. Test and Demonstration.","pri":"Must","comp":"Engagement"}'::jsonb, 8, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 9, '{"stmt":"Waypoints advance rank on verified behavior only (profile complete, first Expedition, sustained Rhythm plus Crew service, capstone), never on purchases.","fit":"No purchase advances rank; every rank maps to verifiable behaviors. Inspection.","pri":"Must","comp":"Engagement"}'::jsonb, 9, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 10, '{"stmt":"ProofRail signs each completion record with a hash, RFC 3161 timestamp, course and version, and requirement attestations, appends it to a transparency log, and verifies publicly without a Fathers.com account.","fit":"A third party verifies a certificate while the platform is offline; revocation is checked on every verify; zero false-valids. Test.","pri":"Must","comp":"ProofRail"}'::jsonb, 10, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 11, '{"stmt":"Institutional reporting exposes completion, attendance, and certificate validity only, always aggregated with a minimum cohort size of ten; assessment scores are never visible to any institution.","fit":"No employer, court, corrections, or military view returns an individual score or a sub-ten cohort. Inspection and Test.","pri":"Must","comp":"Institutional Modes"}'::jsonb, 11, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 12, '{"stmt":"Corrections mode runs a full class session offline, captures attendance and module completion, and syncs verified completions when connectivity returns.","fit":"A facilitator runs a session with no connectivity and syncs later with no data loss. Demonstration and Test.","pri":"Must","comp":"Institutional Modes"}'::jsonb, 12, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 13, '{"stmt":"A crisis disclosure in free text routes to a trained human within one hour, pauses all gamification and nudges for that member, and surfaces professional resources, never punitively and never as automated therapy.","fit":"A seeded disclosure triggers routing within one hour and a gamification pause. Test and Drill.","pri":"Must","comp":"Community"}'::jsonb, 13, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 14, '{"stmt":"Voice mode delivers the assessment eyes-free with streaming speech, grounded clarification from the curated corpus only, and full tap parity with mid-item switching.","fit":"End-of-speech to first audio under 1.5 s p90; semantic mapping at or above 95 percent; any member can switch to tap without loss. Test.","pri":"Should","comp":"Voice Mode"}'::jsonb, 14, 'Seed', now()),
  ('prd-fathering-excellence', 'fr', 15, '{"stmt":"The knowledge agent answers only from the vetted corpus with mandatory citations, files a content-gap ticket when coverage is missing, and lives behind the plan rather than as a front-door chatbot.","fit":"Zero uncited generative claims in the audit sample; out-of-corpus probes defer honestly. Test.","pri":"Should","comp":"Knowledge Agent"}'::jsonb, 15, 'Seed', now()),
  ('prd-fathering-excellence', 'nfr', 1, '{"stmt":"The assessment write path sustains modeled launch peak (about 420 writes per second) without blocking the UI.","fit":"A synthetic run at twice modeled peak (10,000 concurrent sessions) holds the save budget. Load test.","pri":"Must","comp":"Assessment Engine"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'nfr', 2, '{"stmt":"The platform meets WCAG 2.1 AA and Section 508 globally, including keyboard paths, screen-reader labels on the 1-to-5 control, captions, and transcripts.","fit":"An accessibility audit passes AA on every launch surface. Inspection and Test.","pri":"Must","comp":"Assessment Engine"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'nfr', 3, '{"stmt":"Console roles require MFA; staff access is least-privilege with break-glass audit; secrets live in a managed vault.","fit":"No console login without MFA; break-glass reads land in the audit log. Inspection and Test.","pri":"Must","comp":"Institutional Modes"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'nfr', 4, '{"stmt":"Backup and disaster recovery meet RPO 1 hour and RTO 4 hours with a quarterly restore drill.","fit":"A restore drill meets the objectives. Test.","pri":"Must","comp":"ProofRail"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'nfr', 5, '{"stmt":"The assessment path holds 99.9 percent availability during the launch wave.","fit":"Measured uptime on the assessment path meets the target. Test.","pri":"Should","comp":"Assessment Engine"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'eval', 1, '{"dim":"Voice semantic mapping","metric":"Colloquial answer to 1-to-5 mapping accuracy against a human-labeled set, stratified by dialect","thresh":"at or above 95%; below 92% blocks that cohort","exec":"Agent","comp":"Voice Mode"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'eval', 2, '{"dim":"Voice grounding guardrail","metric":"Share of clarification answers drawn only from the curated corpus; out-of-corpus deferral rate","thresh":"100% grounded; improvised interpretation is a hard fail","comp":"Voice Mode"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'eval', 3, '{"dim":"Knowledge agent hallucination guardrail","metric":"Uncited generative claims in the audit sample","thresh":"zero uncited claims","exec":"Agent","comp":"Knowledge Agent"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'eval', 4, '{"dim":"Knowledge agent gap handling","metric":"Out-of-corpus probes that defer honestly and file a gap ticket","thresh":"at or above 99%","comp":"Knowledge Agent"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 1, '{"entity":"Users (father accounts)","sens":"Personal, no sensitive-category fields"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 2, '{"entity":"Children records (life-stage and birth-year band only)","sens":"Minimized; no minor PII"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 3, '{"entity":"Assessment responses and scores","sens":"Personal and sensitive; strictest RLS"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 4, '{"entity":"Consents (research, comparison, marketing)","sens":"Personal; separate revocable records"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 5, '{"entity":"Certificates and verification records","sens":"Personal; public verify exposes initials and compliance only"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'data_entities', 6, '{"entity":"Crisis and moderation cases","sens":"Sensitive; trained-human access only"}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'interfaces', 1, '{"iface":"Identity (SSO)","req":"SAML and OIDC with SCIM for employer seat provisioning","fit":"Employer members claim seats via SSO; the aggregate wall applies from the first screen.","comp":"Institutional Modes"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'interfaces', 2, '{"iface":"Payments","req":"Subscription billing, course and store checkout, marketplace payouts, tax","fit":"Membership, courses, store, and leader payouts transact through the processor.","comp":"Community"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'interfaces', 3, '{"iface":"Media platform","req":"On-demand module delivery and embedded third-party livestreams at launch","fit":"The app never proxies video bytes. Inspection.","comp":"Community"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'interfaces', 4, '{"iface":"ProofRail verification service","req":"Signing, timestamping, transparency log, revocation, public verify endpoint","fit":"Certificates verify independently of the platform. Test.","comp":"ProofRail"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'interfaces', 5, '{"iface":"Court verification","req":"Public code and QR verification returning course, seat-time compliance, and issue date only","fit":"A coordinator verifies with no account and no member data beyond the certificate.","comp":"Institutional Modes"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 1, '{"name":"Micah Canfield","role":"Owner; decision authority on instrument, pricing, naming, partners"}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 2, '{"name":"Tim Harris","role":"Product Manager; phase gatekeeper and scope discipline"}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 3, '{"name":"Alon Arad","role":"CTO; architecture, ProofRail, security posture"}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 4, '{"name":"Erik Companhone","role":"SWE lead; assessment engine, plan engine, consoles"}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 5, '{"name":"Huy Tran","role":"SWE; community, engagement, events, commerce"}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'people', 6, '{"name":"Andy Lan","role":"SWE; data model, analytics spine, institutional modes"}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 1, '{"term":"WAFA","def":"Weekly Active Fathering Actions; the mission North Star."}'::jsonb, 1, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 2, '{"term":"Verified Completion","def":"A ProofRail-signed record of a completed assessment, Expedition, or course."}'::jsonb, 2, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 3, '{"term":"Crew","def":"The 5-to-8-man small group; the retention unit."}'::jsonb, 3, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 4, '{"term":"Anchor","def":"The paired accountability man inside a Crew."}'::jsonb, 4, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 5, '{"term":"Expedition","def":"A fixed-length cohort challenge with daily actions."}'::jsonb, 5, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 6, '{"term":"The Rhythm","def":"The weekly logged intentional fathering action."}'::jsonb, 6, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 7, '{"term":"Waypoints","def":"The verified-behavior rank ladder."}'::jsonb, 7, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 8, '{"term":"ProofRail","def":"The signing, timestamping, and verification service."}'::jsonb, 8, 'Seed', now()),
  ('prd-fathering-excellence', 'glossary', 9, '{"term":"Mars rule","def":"Proof must verify even if the platform is offline."}'::jsonb, 9, 'Seed', now())
on conflict (project_id, field_id, k) do update set data = excluded.data, pos = excluded.pos, rev = 1;

commit;
