// ReqPub v2.51 - the MCP server. One function, JWT off, MCP over Streamable
// HTTP: JSON-RPC 2.0 initialize, tools/list, tools/call. Server name reqpub,
// version from APP_VERSION, capabilities tools only.
//
// A read surface for the record and a door into the inbox, never a hand on
// the pen. Five read tools return authored and cryptographic facts; the one
// write tool, reqpub_propose, lands an ordinary comm for human triage and is
// doubly gated, key and project, both default off. No tool touches
// project_fields, field_rows, versions, version_approvals, sign_requests,
// receipts, webhooks, or keys. The v2.34.2 boundary holds: no tokens, no
// email addresses, in any response.
//
// Auth: Authorization: Bearer rqp_live_<32 base62>. The function hashes the
// presented key and asks mcp_auth; the key itself is never stored or logged.
// Every call is admitted through mcp_gate, 60 per key per minute, and every
// outcome appends one row to the insert-only mcp_audit_log.
//
// This file is written so Node can import it directly for the unit suite:
// the handler is pure and injectable, and the Deno tail only runs under
// Deno. The dashboard paste is generated by scripts/bundle-mcp-function.mjs
// and pinned byte for byte by tests/mcp-scheme.test.mjs.

import { APP_VERSION, canonicalJson, sha256Hex, versionFingerprint } from "./core.js";

const env = (k) => (typeof Deno !== "undefined" && Deno.env ? Deno.env.get(k) : undefined) ?? "";
const SUPABASE_URL = env("SUPABASE_URL");
const SERVICE_KEY = env("SUPABASE_SERVICE_ROLE_KEY");

export const PROTOCOL_VERSION = "2025-03-26";
export const SERVER_INFO = { name: "reqpub", version: APP_VERSION };

export const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

/* The bearer must look like a ReqPub key before anything is hashed. The
   whole presented string is hashed, prefix included, so the stored sha256
   commits to the exact credential. */
export function parseBearer(header) {
  const m = /^Bearer\s+(rqp_live_[0-9A-Za-z]{32})$/.exec(String(header || "").trim());
  return m ? m[1] : null;
}

/* Tool definitions. reqpub_propose appears only when both gates can be on:
   the key allows proposing and at least one in-scope project has authored
   the control on. */
export function toolDefs(includePropose) {
  const t = [
    {
      name: "reqpub_list_projects",
      description: "List the projects this key can read: id, name, createdAt, latest baseline label and status, practice flag. Authored and cryptographic facts only.",
      inputSchema: { type: "object", properties: {}, additionalProperties: false },
    },
    {
      name: "reqpub_get_baseline",
      description: "The stored version row for a project: label, seq, status, note, authorName, createdAt, snapshot, and the fingerprint computed with the published recipe. This is the spec an agent executes against.",
      inputSchema: {
        type: "object",
        properties: { projectId: { type: "string" }, seq: { type: "integer" } },
        required: ["projectId"], additionalProperties: false,
      },
    },
    {
      name: "reqpub_get_signature_status",
      description: "Per sign request on a baseline: signerName, signerRole, status, sentAt, signedAt, receiptId when sealed. No tokens, no email addresses.",
      inputSchema: {
        type: "object",
        properties: { projectId: { type: "string" }, seq: { type: "integer" } },
        required: ["projectId"], additionalProperties: false,
      },
    },
    {
      name: "reqpub_get_receipt",
      description: "A sealed acceptance receipt by id: the stored receipt JSON, its Ed25519 signature, the signing key id, and the timestamp status. Verify offline per docs/VERIFY.md.",
      inputSchema: {
        type: "object",
        properties: { receiptId: { type: "string" } },
        required: ["receiptId"], additionalProperties: false,
      },
    },
    {
      name: "reqpub_verify_chain",
      description: "Run the project's activity-chain verification and return its output verbatim.",
      inputSchema: {
        type: "object",
        properties: { projectId: { type: "string" } },
        required: ["projectId"], additionalProperties: false,
      },
    },
  ];
  if (includePropose) {
    t.push({
      name: "reqpub_propose",
      description: "Record a proposal for human review on a project that allows it. Lands in the same inbox as every other inbound submission. Agents propose; humans accept.",
      inputSchema: {
        type: "object",
        properties: {
          projectId: { type: "string" }, subject: { type: "string" },
          body: { type: "string" }, targetRef: { type: "string" },
        },
        required: ["projectId", "subject", "body"], additionalProperties: false,
      },
    });
  }
  return t;
}

const rpcResult = (id, result) => ({ jsonrpc: "2.0", id: id ?? null, result });
const rpcError = (id, code, message) => ({ jsonrpc: "2.0", id: id ?? null, error: { code, message } });
const toolJson = (data) => ({ content: [{ type: "text", text: JSON.stringify(data) }] });
const toolErr = (message) => ({ content: [{ type: "text", text: message }], isError: true });

const isStr = (v) => typeof v === "string" && v.length > 0;
const isIntOrAbsent = (v) => v === undefined || Number.isInteger(v);

/* The whole protocol, pure and injectable. ctx carries the authenticated
   key facts and an rpc(fn, args) bridge; the Deno tail wires the real
   service client, the unit suite wires stubs. Returns {status, body}. */
export async function handleRpc(msg, ctx) {
  if (!msg || msg.jsonrpc !== "2.0" || !isStr(msg.method)) {
    return { status: 200, body: rpcError(msg && msg.id, -32600, "invalid request") };
  }
  const a = ctx.auth;
  if (msg.method === "initialize") {
    return {
      status: 200,
      body: rpcResult(msg.id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: SERVER_INFO,
      }),
    };
  }
  if (msg.method === "notifications/initialized") return { status: 202, body: null };
  if (msg.method === "tools/list") {
    let include = false;
    if (a.proposeEnabled) {
      const vis = await ctx.rpc("mcp_propose_visible", { p_org: a.orgId, p_scope: a.projectIds });
      include = !!(vis && vis.visible);
    }
    return { status: 200, body: rpcResult(msg.id, { tools: toolDefs(include) }) };
  }
  if (msg.method !== "tools/call") {
    return { status: 200, body: rpcError(msg.id, -32601, "method not found") };
  }

  const name = msg.params && msg.params.name;
  const args = (msg.params && msg.params.arguments) || {};
  if (!isStr(name)) return { status: 200, body: rpcError(msg.id, -32602, "tool name required") };
  const paramsHash = await sha256Hex(canonicalJson(args));

  const gate = await ctx.rpc("mcp_gate", { p_key: a.keyId, p_tool: name, p_params_hash: paramsHash });
  if (!gate || gate.ok !== true) {
    return { status: 429, body: rpcError(msg.id, -32000, "rate limited") };
  }
  const audit = (status) => ctx.rpc("mcp_audit_append",
    { p_key: a.keyId, p_tool: name, p_params_hash: paramsHash, p_status: status });

  try {
    let out = null;
    if (name === "reqpub_list_projects") {
      out = await ctx.rpc("mcp_list_projects", { p_org: a.orgId, p_scope: a.projectIds });
    } else if (name === "reqpub_get_baseline") {
      if (!isStr(args.projectId) || !isIntOrAbsent(args.seq)) {
        return { status: 200, body: rpcError(msg.id, -32602, "projectId required; seq must be an integer") };
      }
      out = await ctx.rpc("mcp_get_baseline",
        { p_org: a.orgId, p_scope: a.projectIds, p_project: args.projectId, p_seq: args.seq ?? null });
      if (out && out.ok) {
        out.fingerprint = await versionFingerprint({ label: out.label, seq: out.seq, snapshot: out.snapshot });
      }
    } else if (name === "reqpub_get_signature_status") {
      if (!isStr(args.projectId) || !isIntOrAbsent(args.seq)) {
        return { status: 200, body: rpcError(msg.id, -32602, "projectId required; seq must be an integer") };
      }
      out = await ctx.rpc("mcp_signature_status",
        { p_org: a.orgId, p_scope: a.projectIds, p_project: args.projectId, p_seq: args.seq ?? null });
    } else if (name === "reqpub_get_receipt") {
      if (!isStr(args.receiptId)) {
        return { status: 200, body: rpcError(msg.id, -32602, "receiptId required") };
      }
      out = await ctx.rpc("mcp_get_receipt",
        { p_org: a.orgId, p_scope: a.projectIds, p_receipt: args.receiptId });
    } else if (name === "reqpub_verify_chain") {
      if (!isStr(args.projectId)) {
        return { status: 200, body: rpcError(msg.id, -32602, "projectId required") };
      }
      out = await ctx.rpc("mcp_verify_chain",
        { p_org: a.orgId, p_scope: a.projectIds, p_project: args.projectId });
    } else if (name === "reqpub_propose") {
      if (!isStr(args.projectId) || !isStr(args.subject) || !isStr(args.body)) {
        return { status: 200, body: rpcError(msg.id, -32602, "projectId, subject, and body required") };
      }
      out = await ctx.rpc("mcp_propose", {
        p_key: a.keyId, p_project: args.projectId, p_subject: args.subject,
        p_body: args.body, p_target: isStr(args.targetRef) ? args.targetRef : "",
      });
    } else {
      await audit("denied");
      return { status: 200, body: rpcError(msg.id, -32601, "unknown tool") };
    }

    if (!out || out.ok !== true) {
      await audit("denied");
      const reason = out && typeof out.error === "string" ? out.error : "denied";
      return { status: 200, body: rpcResult(msg.id, toolErr(reason)) };
    }
    return { status: 200, body: rpcResult(msg.id, toolJson(out)) };
  } catch {
    await audit("error");
    return { status: 200, body: rpcError(msg.id, -32000, "internal error") };
  }
}

// ---------------------------------------------------------------------------
// The Deno tail: real service client, bearer auth, CORS, dispatch. Node
// never executes past this guard, so the exported logic above is what the
// unit suite tests and what the paste ships.
// ---------------------------------------------------------------------------
if (typeof Deno !== "undefined" && Deno.serve) {
  const { createClient } = await import("https://esm.sh/@supabase/supabase-js@2");
  const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });
  const rpc = async (fn, args) => {
    const { data, error } = await sb.rpc(fn, args);
    if (error) return { ok: false, error: "rpc_failed" };
    return data;
  };
  const json = (code, body) => new Response(body === null ? "" : JSON.stringify(body), {
    status: code, headers: { ...cors, "Content-Type": "application/json" } });
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json(405, rpcError(null, -32600, "POST only"));
    let msg = null;
    try { msg = await req.json(); }
    catch { return json(200, rpcError(null, -32700, "parse error")); }
    const key = parseBearer(req.headers.get("authorization"));
    if (!key) return json(401, rpcError(msg && msg.id, -32001, "bearer key required"));
    const auth = await rpc("mcp_auth", { p_key_hash: await sha256Hex(key) });
    if (!auth || auth.ok !== true) {
      return json(401, rpcError(msg && msg.id, -32001, "invalid or revoked key"));
    }
    const out = await handleRpc(msg, {
      auth: {
        keyId: auth.keyId, orgId: auth.orgId, label: auth.label,
        projectIds: auth.projectIds ?? null, proposeEnabled: !!auth.proposeEnabled,
      },
      rpc,
    });
    return json(out.status, out.body);
  });
}
